\input texinfo
@documentencoding UTF-8

@ifnottex
@paragraphindent 0
@end ifnottex
@node Top
@top Top

s21 BrickGame v2.0

@enumerate 
@item
To install:
@itemize
@item
use command 'make install'
@item
installation will start to build/cli and build/desktop directory
@end itemize

@item
To uninstall:
@itemize
@item
use command 'make uninstall'
@end itemize

@end enumerate

@bye